/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'agutheil' at '19.05.15 20:46' with Gradle 2.1
 *
 * @author agutheil, @date 19.05.15 20:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
